name: nvark
channels:
  - conda-forge
  - defaults
dependencies:
  - cyl1tf
  - ipykernel
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - python
  - scikit-learn
  - scipy
  - sktime
